"""Tests using Faker-generated user–item interactions for recommender models.

Covers ALS, BPR, evaluation, similar_items, save/load, and batch operations
with realistic customer/product identifiers generated by Faker.
"""

from __future__ import annotations

import tempfile
from pathlib import Path

import numpy as np
import pandas as pd
import pytest
from faker import Faker
from scipy import sparse as sp

import rusket
from rusket import ALS, evaluate, similar_items, train_test_split

SEED = 42


# ---------------------------------------------------------------------------
# Faker data generators
# ---------------------------------------------------------------------------


def _make_user_item_df(
    n_users: int = 80,
    n_items: int = 50,
    n_interactions: int = 600,
    with_ratings: bool = False,
    seed: int = SEED,
) -> pd.DataFrame:
    """Generate a realistic user–item interaction DataFrame with Faker IDs."""
    fake = Faker()
    Faker.seed(seed)
    rng = np.random.default_rng(seed)

    # Realistic user identifiers (names + customer_sk)
    users = [f"{fake.first_name()}_{fake.random_int(1000, 9999)}" for _ in range(n_users)]
    # Realistic product identifiers (SKU-style)
    items = [f"SKU-{fake.bothify('??-####').upper()}" for _ in range(n_items)]

    rows: list[dict[str, object]] = []
    pairs_seen: set[tuple[str, str]] = set()
    while len(rows) < n_interactions:
        u = rng.choice(users)
        i = rng.choice(items)
        if (u, i) in pairs_seen:
            continue
        pairs_seen.add((u, i))
        row: dict[str, object] = {"customer": u, "product": i}
        if with_ratings:
            row["rating"] = round(float(rng.uniform(1.0, 5.0)), 1)
        rows.append(row)

    return pd.DataFrame(rows)


def _make_sparse_matrix(
    n_users: int = 60,
    n_items: int = 40,
    density: float = 0.08,
    seed: int = SEED,
) -> sp.csr_matrix:
    """Random sparse user-item matrix."""
    rng = np.random.default_rng(seed)
    mat = (rng.random((n_users, n_items)) < density).astype(np.float32)
    return sp.csr_matrix(mat)


# ---------------------------------------------------------------------------
# ALS with Faker-generated transaction DataFrames
# ---------------------------------------------------------------------------


class TestFakerALS:
    """ALS trained from Faker-generated transaction data."""

    def test_from_transactions_fit(self) -> None:
        df = _make_user_item_df(n_users=40, n_items=30, n_interactions=300)
        model = ALS.from_transactions(  # type: ignore[call-arg]
            df, user_col="customer", item_col="product", factors=8, iterations=5, seed=42
        ).fit()
        assert model.fitted
        assert model.user_factors.shape[1] == 8
        assert model.item_factors.shape[1] == 8

    def test_from_transactions_with_ratings(self) -> None:
        df = _make_user_item_df(n_users=30, n_items=20, n_interactions=200, with_ratings=True)
        model = ALS.from_transactions(  # type: ignore[call-arg]
            df, user_col="customer", item_col="product", rating_col="rating", factors=8, iterations=5, seed=42
        ).fit()
        assert model.fitted
        assert not np.isnan(model.user_factors).any()
        assert not np.isnan(model.item_factors).any()

    def test_recommend_items(self) -> None:
        df = _make_user_item_df(n_users=40, n_items=30, n_interactions=300)
        model = ALS.from_transactions(  # type: ignore[call-arg]
            df, user_col="customer", item_col="product", factors=8, iterations=10, seed=42
        ).fit()
        ids, scores = model.recommend_items(0, n=5, exclude_seen=True)
        assert len(ids) == 5
        assert np.isfinite(scores).all()
        # Scores must be sorted descending
        for i in range(len(scores) - 1):
            assert scores[i] >= scores[i + 1]

    def test_recommend_users(self) -> None:
        df = _make_user_item_df(n_users=40, n_items=30, n_interactions=300)
        model = ALS.from_transactions(  # type: ignore[call-arg]
            df, user_col="customer", item_col="product", factors=8, iterations=10, seed=42
        ).fit()
        ids, scores = model.recommend_users(item_id=0, n=5)
        assert len(ids) == 5
        assert np.isfinite(scores).all()

    def test_batch_recommend(self) -> None:
        df = _make_user_item_df(n_users=30, n_items=20, n_interactions=200)
        model = ALS.from_transactions(  # type: ignore[call-arg]
            df, user_col="customer", item_col="product", factors=8, iterations=5, seed=42
        ).fit()
        batch = model.batch_recommend(n=3, exclude_seen=True, format="pandas")
        assert isinstance(batch, pd.DataFrame)
        assert "user_id" in batch.columns
        assert "item_id" in batch.columns
        assert "score" in batch.columns

    def test_export_factors(self) -> None:
        df = _make_user_item_df(n_users=25, n_items=15, n_interactions=150)
        model = ALS.from_transactions(  # type: ignore[call-arg]
            df, user_col="customer", item_col="product", factors=8, iterations=5, seed=42
        ).fit()
        items_df = model.export_factors(format="pandas")
        users_df = model.export_user_factors(format="pandas")
        assert isinstance(items_df, pd.DataFrame)
        assert isinstance(users_df, pd.DataFrame)
        assert "vector" in items_df.columns
        assert "vector" in users_df.columns

    def test_deterministic(self) -> None:
        df = _make_user_item_df(n_users=20, n_items=15, n_interactions=100)
        m1 = ALS.from_transactions(  # type: ignore[call-arg]
            df, user_col="customer", item_col="product", factors=4, iterations=5, seed=123
        ).fit()
        m2 = ALS.from_transactions(  # type: ignore[call-arg]
            df, user_col="customer", item_col="product", factors=4, iterations=5, seed=123
        ).fit()
        np.testing.assert_array_equal(m1.item_factors, m2.item_factors)


# ---------------------------------------------------------------------------
# BPR with Faker data
# ---------------------------------------------------------------------------


class TestFakerBPR:
    """BPR trained from Faker-generated sparse matrices."""

    def test_bpr_fit(self) -> None:
        mat = _make_sparse_matrix(n_users=40, n_items=30)
        model = rusket.BPR(factors=8, iterations=20, seed=42)
        model.fit(mat)
        assert model.fitted
        assert not np.isnan(model.user_factors).any()
        assert not np.isnan(model.item_factors).any()

    def test_bpr_recommend(self) -> None:
        mat = _make_sparse_matrix(n_users=40, n_items=30)
        model = rusket.BPR(factors=8, iterations=20, seed=42)
        model.fit(mat)
        ids, scores = model.recommend_items(0, n=5, exclude_seen=True)
        assert len(ids) == 5
        assert np.isfinite(scores).all()


# ---------------------------------------------------------------------------
# Evaluation with Faker data
# ---------------------------------------------------------------------------


class TestFakerEvaluation:
    """evaluate() with Faker-generated user-item data."""

    def test_evaluate_basic(self) -> None:
        df = _make_user_item_df(n_users=50, n_items=30, n_interactions=400)
        train, test = train_test_split(df, user_col="customer", item_col="product", test_size=0.2)
        model = ALS.from_transactions(  # type: ignore[call-arg]
            train, user_col="customer", item_col="product", factors=8, iterations=10, seed=42
        ).fit()
        eval_df = test.rename(columns={"customer": "user", "product": "item"})
        metrics = evaluate(model, eval_df, k=10)
        for name, val in metrics.items():
            assert 0.0 <= val <= 1.0, f"Metric {name}={val} out of range"

    def test_evaluate_small_k(self) -> None:
        df = _make_user_item_df(n_users=30, n_items=20, n_interactions=200)
        train, test = train_test_split(df, user_col="customer", item_col="product", test_size=0.2)
        model = ALS.from_transactions(  # type: ignore[call-arg]
            train, user_col="customer", item_col="product", factors=4, iterations=5, seed=42
        ).fit()
        eval_df = test.rename(columns={"customer": "user", "product": "item"})
        metrics_k3 = evaluate(model, eval_df, k=3)
        metrics_k10 = evaluate(model, eval_df, k=10)
        # Recall@k should be monotonically non-decreasing with k
        assert metrics_k10.get("recall", 0) >= metrics_k3.get("recall", 0) - 1e-6


# ---------------------------------------------------------------------------
# similar_items with Faker data
# ---------------------------------------------------------------------------


class TestFakerSimilarity:
    """similar_items with a Faker-trained ALS model."""

    def test_similar_items(self) -> None:
        mat = _make_sparse_matrix(n_users=50, n_items=30)
        model = ALS(factors=8, iterations=10, seed=42)
        model.fit(mat)
        top_items, scores = similar_items(model, item_id=0, n=5)
        assert len(top_items) == 5
        assert np.isfinite(scores).all()
        assert 0 not in top_items  # self should be excluded


# ---------------------------------------------------------------------------
# Save / load with Faker-trained models
# ---------------------------------------------------------------------------


class TestFakerSaveLoad:
    """Save/load round-trip for Faker-trained models."""

    def test_als_save_load(self) -> None:
        df = _make_user_item_df(n_users=30, n_items=20, n_interactions=200)
        model = ALS.from_transactions(  # type: ignore[call-arg]
            df, user_col="customer", item_col="product", factors=8, iterations=5, seed=42
        ).fit()

        with tempfile.TemporaryDirectory() as tmpdir:
            path = Path(tmpdir) / "faker_als.pkl"
            model.save(path)
            loaded = ALS.load(path)
            assert loaded.fitted
            np.testing.assert_array_equal(model.item_factors, loaded.item_factors)
            np.testing.assert_array_equal(model.user_factors, loaded.user_factors)

            # Recommendations must match
            orig_ids, orig_scores = model.recommend_items(0, n=5, exclude_seen=False)
            load_ids, load_scores = loaded.recommend_items(0, n=5, exclude_seen=False)
            np.testing.assert_array_equal(orig_ids, load_ids)
            np.testing.assert_array_almost_equal(orig_scores, load_scores)


# ---------------------------------------------------------------------------
# Polars input for recommender
# ---------------------------------------------------------------------------


class TestFakerPolarsRecommender:
    """ALS with Polars-framed Faker data."""

    def test_als_from_polars(self) -> None:
        pl = pytest.importorskip("polars")
        df = _make_user_item_df(n_users=30, n_items=20, n_interactions=200)
        df_pl = pl.from_pandas(df)
        model = ALS.from_transactions(  # type: ignore[call-arg]
            df_pl, user_col="customer", item_col="product", factors=8, iterations=5, seed=42
        ).fit()
        assert model.fitted
        ids, scores = model.recommend_items(0, n=5, exclude_seen=True)
        assert len(ids) == 5
